/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioQuinze;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
    
        int numero;
        
        Scanner leitor = new Scanner (System.in);
        
        System.out.println("Por favor informe um numero");
        
        numero = leitor.nextInt ();
        
        if (numero >=100 && numero<= 200) {
            System.out.println ("Esta dentro do intervalo");
        } else {
            System.out.println ("Esta fora do intervalo");
        }   
        
    }
    
}