/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeiroProjeto;

public class App {

   
    public static void main(String[] args) {
        //Comentário de linha
        
        /* Comentário de bloco
        Minha primeira linha de comentário
        Segunda linha de comentário...
        */
        
        /** 
        Comentário de documetação 
        */
        System.out.println ("Ola Mundo!");
        System.out.println ("Meu segundo comando de saida");
        
    }
}
